### ISSUE TITLE
Questions about loss & data

### ISSUE THREAD

**Issue by Dou-Yiming** [facebookresearch/3D-Vision-and-Touch#6]
Hi! Thanks for the exciting work.
Recently I've been trying to combine the model of this work with a new dataset that only contains .obj mesh files with visual & tactile readings, and I encounter several questions:
1. Why do you multiply the chamfer loss with a "loss_coeff" during the training and testing process? What's the meaning of this coefficient?
2. In you dataset, there's an item in the scene_info called "samples", which stands for the local point cloud based on my understanding, may I ask how did you obtain this point cloud? Is it possible that I can sample this point cloud based on the .obj mesh file (similar to the generation of global point clouds using "batch_sample" function)?
3. What's the unit of your dataset and loss? Is it centimeter or something else?

Thank you!

**Comment by EdwardSmith1884** [comment]
Hi, 

1. loss_coeff can be ignore. It is just a scaling factor so that the chamfer distance is in a nice range. 
2. I basically compute an orthographic depth map from the perspective of each finger tip and transform the depth values within a small range into a point cloud using the finger pose . But if you want to do this yourself you should check out my [new project page](https://github.com/facebookresearch/Active-3D-Vision-and-Touch). It has a simulator for touching object where you can extract the local point clouds easily. [This notebook](https://github.com/facebookresearch/Active-3D-Vision-and-Touch/blob/main/notebook/simulator.ipynb) shows you how to use it and has an example where I visualize the point cloud on the object under "Visualize the touches" section. 
3. There is no standard unit, other than the objects in my dataset having a standard scale, over which distance is defined.

**Comment by Dou-Yiming** [comment]
Thanks so much for the quick reply! I'll look into the new project.
I have two further questions:
1. Since there is no standard unit, there should be some normalization method to deal with the problem that the sizes of different objects vary a lot (e.g., the length of a desk may be larger than 1 meter while a spoon may be just several centimeters). Did you use any methods to normalize the point cloud, such as dividing each coordinate by the maximum coordinate value to scale them into [-1, 1]?
2. In your data-loader, the GT point cloud is multiplied with 0.5, and then added with 0.6, what's the meaning of these two numbers?

**Comment by EdwardSmith1884** [comment]
1. This was performed, I think the models all have their largest dimension scaled to .5 
2. This transformation is to set the model dimension to .5 instead of 1 so that the objects size with respect to the hand is sensible. The translation of .6 is only applied to the z dimension and it is performed so that the objects do not intersect the ground in pybullet, allowing the hand to move freely around its surface. Does that make sense?

**Comment by Dou-Yiming** [comment]
Okay thanks! I can understand it now.
